/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	pipelinev1alpha1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
	scheme "github.com/tektoncd/pipeline/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TaskTestRunsGetter has a method to return a TaskTestRunInterface.
// A group's client should implement this interface.
type TaskTestRunsGetter interface {
	TaskTestRuns(namespace string) TaskTestRunInterface
}

// TaskTestRunInterface has methods to work with TaskTestRun resources.
type TaskTestRunInterface interface {
	Create(ctx context.Context, taskTestRun *pipelinev1alpha1.TaskTestRun, opts v1.CreateOptions) (*pipelinev1alpha1.TaskTestRun, error)
	Update(ctx context.Context, taskTestRun *pipelinev1alpha1.TaskTestRun, opts v1.UpdateOptions) (*pipelinev1alpha1.TaskTestRun, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, taskTestRun *pipelinev1alpha1.TaskTestRun, opts v1.UpdateOptions) (*pipelinev1alpha1.TaskTestRun, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*pipelinev1alpha1.TaskTestRun, error)
	List(ctx context.Context, opts v1.ListOptions) (*pipelinev1alpha1.TaskTestRunList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *pipelinev1alpha1.TaskTestRun, err error)
	TaskTestRunExpansion
}

// taskTestRuns implements TaskTestRunInterface
type taskTestRuns struct {
	*gentype.ClientWithList[*pipelinev1alpha1.TaskTestRun, *pipelinev1alpha1.TaskTestRunList]
}

// newTaskTestRuns returns a TaskTestRuns
func newTaskTestRuns(c *TektonV1alpha1Client, namespace string) *taskTestRuns {
	return &taskTestRuns{
		gentype.NewClientWithList[*pipelinev1alpha1.TaskTestRun, *pipelinev1alpha1.TaskTestRunList](
			"tasktestruns",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *pipelinev1alpha1.TaskTestRun { return &pipelinev1alpha1.TaskTestRun{} },
			func() *pipelinev1alpha1.TaskTestRunList { return &pipelinev1alpha1.TaskTestRunList{} },
		),
	}
}
