/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	pipelinev1alpha1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
	scheme "github.com/tektoncd/pipeline/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TaskTestSuitesGetter has a method to return a TaskTestSuiteInterface.
// A group's client should implement this interface.
type TaskTestSuitesGetter interface {
	TaskTestSuites(namespace string) TaskTestSuiteInterface
}

// TaskTestSuiteInterface has methods to work with TaskTestSuite resources.
type TaskTestSuiteInterface interface {
	Create(ctx context.Context, taskTestSuite *pipelinev1alpha1.TaskTestSuite, opts v1.CreateOptions) (*pipelinev1alpha1.TaskTestSuite, error)
	Update(ctx context.Context, taskTestSuite *pipelinev1alpha1.TaskTestSuite, opts v1.UpdateOptions) (*pipelinev1alpha1.TaskTestSuite, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*pipelinev1alpha1.TaskTestSuite, error)
	List(ctx context.Context, opts v1.ListOptions) (*pipelinev1alpha1.TaskTestSuiteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *pipelinev1alpha1.TaskTestSuite, err error)
	TaskTestSuiteExpansion
}

// taskTestSuites implements TaskTestSuiteInterface
type taskTestSuites struct {
	*gentype.ClientWithList[*pipelinev1alpha1.TaskTestSuite, *pipelinev1alpha1.TaskTestSuiteList]
}

// newTaskTestSuites returns a TaskTestSuites
func newTaskTestSuites(c *TektonV1alpha1Client, namespace string) *taskTestSuites {
	return &taskTestSuites{
		gentype.NewClientWithList[*pipelinev1alpha1.TaskTestSuite, *pipelinev1alpha1.TaskTestSuiteList](
			"tasktestsuites",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *pipelinev1alpha1.TaskTestSuite { return &pipelinev1alpha1.TaskTestSuite{} },
			func() *pipelinev1alpha1.TaskTestSuiteList { return &pipelinev1alpha1.TaskTestSuiteList{} },
		),
	}
}
