apiVersion: tekton.dev/v1alpha1
kind: TaskTestRun
metadata:
  generateName: sample-ttr-
  namespace: default
spec:
  taskTestSpec:
    taskRef:
      name: hello-task
    expected:
      results:
        - name: current-date
          value: "2025-08-18"
      env:
      - name: HOME
        value: /root
      - name: PATH
        value: deine mudder
