//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	pod "github.com/tektoncd/pipeline/pkg/apis/pipeline/pod"
	v1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	v1beta1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authority) DeepCopyInto(out *Authority) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(KeyRef)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authority.
func (in *Authority) DeepCopy() *Authority {
	if in == nil {
		return nil
	}
	out := new(Authority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddedRunSpec) DeepCopyInto(out *EmbeddedRunSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddedRunSpec.
func (in *EmbeddedRunSpec) DeepCopy() *EmbeddedRunSpec {
	if in == nil {
		return nil
	}
	out := new(EmbeddedRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedOutcomes) DeepCopyInto(out *ExpectedOutcomes) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]v1.TaskResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StepEnvs != nil {
		in, out := &in.StepEnvs, &out.StepEnvs
		*out = make([]StepEnv, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SuccessStatus != nil {
		in, out := &in.SuccessStatus, &out.SuccessStatus
		*out = new(bool)
		**out = **in
	}
	if in.SuccessReason != nil {
		in, out := &in.SuccessReason, &out.SuccessReason
		*out = new(v1.TaskRunReason)
		**out = **in
	}
	if in.FileSystemContents != nil {
		in, out := &in.FileSystemContents, &out.FileSystemContents
		*out = make([]ExpectedStepFileSystemContent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedOutcomes.
func (in *ExpectedOutcomes) DeepCopy() *ExpectedOutcomes {
	if in == nil {
		return nil
	}
	out := new(ExpectedOutcomes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedStepFileSystemContent) DeepCopyInto(out *ExpectedStepFileSystemContent) {
	*out = *in
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = make([]FileSystemObject, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedStepFileSystemContent.
func (in *ExpectedStepFileSystemContent) DeepCopy() *ExpectedStepFileSystemContent {
	if in == nil {
		return nil
	}
	out := new(ExpectedStepFileSystemContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemObject) DeepCopyInto(out *FileSystemObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemObject.
func (in *FileSystemObject) DeepCopy() *FileSystemObject {
	if in == nil {
		return nil
	}
	out := new(FileSystemObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialWorkspaceContents) DeepCopyInto(out *InitialWorkspaceContents) {
	*out = *in
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = make([]InputFileSystemObject, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialWorkspaceContents.
func (in *InitialWorkspaceContents) DeepCopy() *InitialWorkspaceContents {
	if in == nil {
		return nil
	}
	out := new(InitialWorkspaceContents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputFileSystemObject) DeepCopyInto(out *InputFileSystemObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputFileSystemObject.
func (in *InputFileSystemObject) DeepCopy() *InputFileSystemObject {
	if in == nil {
		return nil
	}
	out := new(InputFileSystemObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyRef) DeepCopyInto(out *KeyRef) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyRef.
func (in *KeyRef) DeepCopy() *KeyRef {
	if in == nil {
		return nil
	}
	out := new(KeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedTaskTestSpec) DeepCopyInto(out *NamedTaskTestSpec) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(TaskTestSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedTaskTestSpec.
func (in *NamedTaskTestSpec) DeepCopy() *NamedTaskTestSpec {
	if in == nil {
		return nil
	}
	out := new(NamedTaskTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedEnvVar) DeepCopyInto(out *ObservedEnvVar) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedEnvVar.
func (in *ObservedEnvVar) DeepCopy() *ObservedEnvVar {
	if in == nil {
		return nil
	}
	out := new(ObservedEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedFileSystemObject) DeepCopyInto(out *ObservedFileSystemObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedFileSystemObject.
func (in *ObservedFileSystemObject) DeepCopy() *ObservedFileSystemObject {
	if in == nil {
		return nil
	}
	out := new(ObservedFileSystemObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedOutcomes) DeepCopyInto(out *ObservedOutcomes) {
	*out = *in
	if in.FileSystemObjects != nil {
		in, out := &in.FileSystemObjects, &out.FileSystemObjects
		*out = new([]ObservedStepFileSystemContent)
		if **in != nil {
			in, out := *in, *out
			*out = make([]ObservedStepFileSystemContent, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = new([]ObservedResults)
		if **in != nil {
			in, out := *in, *out
			*out = make([]ObservedResults, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.StepEnvs != nil {
		in, out := &in.StepEnvs, &out.StepEnvs
		*out = new([]ObservedStepEnv)
		if **in != nil {
			in, out := *in, *out
			*out = make([]ObservedStepEnv, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.SuccessStatus != nil {
		in, out := &in.SuccessStatus, &out.SuccessStatus
		*out = new(ObservedSuccessStatus)
		**out = **in
	}
	if in.SuccessReason != nil {
		in, out := &in.SuccessReason, &out.SuccessReason
		*out = new(ObservedSuccessReason)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedOutcomes.
func (in *ObservedOutcomes) DeepCopy() *ObservedOutcomes {
	if in == nil {
		return nil
	}
	out := new(ObservedOutcomes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedResults) DeepCopyInto(out *ObservedResults) {
	*out = *in
	if in.Want != nil {
		in, out := &in.Want, &out.Want
		*out = new(v1.ParamValue)
		(*in).DeepCopyInto(*out)
	}
	if in.Got != nil {
		in, out := &in.Got, &out.Got
		*out = new(v1.ParamValue)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedResults.
func (in *ObservedResults) DeepCopy() *ObservedResults {
	if in == nil {
		return nil
	}
	out := new(ObservedResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedStepEnv) DeepCopyInto(out *ObservedStepEnv) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]ObservedEnvVar, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedStepEnv.
func (in *ObservedStepEnv) DeepCopy() *ObservedStepEnv {
	if in == nil {
		return nil
	}
	out := new(ObservedStepEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedStepFileSystemContent) DeepCopyInto(out *ObservedStepFileSystemContent) {
	*out = *in
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = make([]ObservedFileSystemObject, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedStepFileSystemContent.
func (in *ObservedStepFileSystemContent) DeepCopy() *ObservedStepFileSystemContent {
	if in == nil {
		return nil
	}
	out := new(ObservedStepFileSystemContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedSuccessReason) DeepCopyInto(out *ObservedSuccessReason) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedSuccessReason.
func (in *ObservedSuccessReason) DeepCopy() *ObservedSuccessReason {
	if in == nil {
		return nil
	}
	out := new(ObservedSuccessReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedSuccessStatus) DeepCopyInto(out *ObservedSuccessStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedSuccessStatus.
func (in *ObservedSuccessStatus) DeepCopy() *ObservedSuccessStatus {
	if in == nil {
		return nil
	}
	out := new(ObservedSuccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePattern) DeepCopyInto(out *ResourcePattern) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePattern.
func (in *ResourcePattern) DeepCopy() *ResourcePattern {
	if in == nil {
		return nil
	}
	out := new(ResourcePattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in RetriesStatus) DeepCopyInto(out *RetriesStatus) {
	{
		in := &in
		*out = make(RetriesStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetriesStatus.
func (in RetriesStatus) DeepCopy() RetriesStatus {
	if in == nil {
		return nil
	}
	out := new(RetriesStatus)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Run) DeepCopyInto(out *Run) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Run.
func (in *Run) DeepCopy() *Run {
	if in == nil {
		return nil
	}
	out := new(Run)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Run) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunList) DeepCopyInto(out *RunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Run, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunList.
func (in *RunList) DeepCopy() *RunList {
	if in == nil {
		return nil
	}
	out := new(RunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunSpec) DeepCopyInto(out *RunSpec) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(v1beta1.TaskRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(EmbeddedRunSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(v1beta1.Params, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(pod.Template)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Workspaces != nil {
		in, out := &in.Workspaces, &out.Workspaces
		*out = make([]v1beta1.WorkspaceBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunSpec.
func (in *RunSpec) DeepCopy() *RunSpec {
	if in == nil {
		return nil
	}
	out := new(RunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleTaskRef) DeepCopyInto(out *SimpleTaskRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleTaskRef.
func (in *SimpleTaskRef) DeepCopy() *SimpleTaskRef {
	if in == nil {
		return nil
	}
	out := new(SimpleTaskRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepAction) DeepCopyInto(out *StepAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepAction.
func (in *StepAction) DeepCopy() *StepAction {
	if in == nil {
		return nil
	}
	out := new(StepAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StepAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepActionList) DeepCopyInto(out *StepActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StepAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepActionList.
func (in *StepActionList) DeepCopy() *StepActionList {
	if in == nil {
		return nil
	}
	out := new(StepActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StepActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepActionSpec) DeepCopyInto(out *StepActionSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(v1.ParamSpecs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]v1.StepResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepActionSpec.
func (in *StepActionSpec) DeepCopy() *StepActionSpec {
	if in == nil {
		return nil
	}
	out := new(StepActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepEnv) DeepCopyInto(out *StepEnv) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepEnv.
func (in *StepEnv) DeepCopy() *StepEnv {
	if in == nil {
		return nil
	}
	out := new(StepEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepEnvironment) DeepCopyInto(out *StepEnvironment) {
	*out = *in
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepEnvironment.
func (in *StepEnvironment) DeepCopy() *StepEnvironment {
	if in == nil {
		return nil
	}
	out := new(StepEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in StepEnvironmentList) DeepCopyInto(out *StepEnvironmentList) {
	{
		in := &in
		*out = make(StepEnvironmentList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepEnvironmentList.
func (in StepEnvironmentList) DeepCopy() StepEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(StepEnvironmentList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in StepFileSystemList) DeepCopyInto(out *StepFileSystemList) {
	{
		in := &in
		*out = make(StepFileSystemList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepFileSystemList.
func (in StepFileSystemList) DeepCopy() StepFileSystemList {
	if in == nil {
		return nil
	}
	out := new(StepFileSystemList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in StepFileSystemMap) DeepCopyInto(out *StepFileSystemMap) {
	{
		in := &in
		*out = make(StepFileSystemMap, len(*in))
		for key, val := range *in {
			var outVal map[string]FileSystemObject
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(map[string]FileSystemObject, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepFileSystemMap.
func (in StepFileSystemMap) DeepCopy() StepFileSystemMap {
	if in == nil {
		return nil
	}
	out := new(StepFileSystemMap)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuiteTaskTestRun) DeepCopyInto(out *SuiteTaskTestRun) {
	*out = *in
	in.TaskTestRunTemplate.DeepCopyInto(&out.TaskTestRunTemplate)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuiteTaskTestRun.
func (in *SuiteTaskTestRun) DeepCopy() *SuiteTaskTestRun {
	if in == nil {
		return nil
	}
	out := new(SuiteTaskTestRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuiteTaskTestRunStatus) DeepCopyInto(out *SuiteTaskTestRunStatus) {
	*out = *in
	in.TaskTestRunStatus.DeepCopyInto(&out.TaskTestRunStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuiteTaskTestRunStatus.
func (in *SuiteTaskTestRunStatus) DeepCopy() *SuiteTaskTestRunStatus {
	if in == nil {
		return nil
	}
	out := new(SuiteTaskTestRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuiteTest) DeepCopyInto(out *SuiteTest) {
	*out = *in
	if in.TaskTestRef != nil {
		in, out := &in.TaskTestRef, &out.TaskTestRef
		*out = new(TaskTestRef)
		**out = **in
	}
	if in.TaskTestSpec != nil {
		in, out := &in.TaskTestSpec, &out.TaskTestSpec
		*out = new(TaskTestSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AllTriesMustSucceed != nil {
		in, out := &in.AllTriesMustSucceed, &out.AllTriesMustSucceed
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuiteTest.
func (in *SuiteTest) DeepCopy() *SuiteTest {
	if in == nil {
		return nil
	}
	out := new(SuiteTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTest) DeepCopyInto(out *TaskTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTest.
func (in *TaskTest) DeepCopy() *TaskTest {
	if in == nil {
		return nil
	}
	out := new(TaskTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestInputs) DeepCopyInto(out *TaskTestInputs) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(v1.Params, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StepEnvs != nil {
		in, out := &in.StepEnvs, &out.StepEnvs
		*out = make([]StepEnv, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WorkspaceContents != nil {
		in, out := &in.WorkspaceContents, &out.WorkspaceContents
		*out = make([]InitialWorkspaceContents, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestInputs.
func (in *TaskTestInputs) DeepCopy() *TaskTestInputs {
	if in == nil {
		return nil
	}
	out := new(TaskTestInputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestList) DeepCopyInto(out *TaskTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestList.
func (in *TaskTestList) DeepCopy() *TaskTestList {
	if in == nil {
		return nil
	}
	out := new(TaskTestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskTestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestRef) DeepCopyInto(out *TaskTestRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestRef.
func (in *TaskTestRef) DeepCopy() *TaskTestRef {
	if in == nil {
		return nil
	}
	out := new(TaskTestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestRun) DeepCopyInto(out *TaskTestRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestRun.
func (in *TaskTestRun) DeepCopy() *TaskTestRun {
	if in == nil {
		return nil
	}
	out := new(TaskTestRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskTestRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestRunList) DeepCopyInto(out *TaskTestRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskTestRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestRunList.
func (in *TaskTestRunList) DeepCopy() *TaskTestRunList {
	if in == nil {
		return nil
	}
	out := new(TaskTestRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskTestRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestRunSpec) DeepCopyInto(out *TaskTestRunSpec) {
	*out = *in
	if in.TaskTestRef != nil {
		in, out := &in.TaskTestRef, &out.TaskTestRef
		*out = new(TaskTestRef)
		**out = **in
	}
	if in.TaskTestSpec != nil {
		in, out := &in.TaskTestSpec, &out.TaskTestSpec
		*out = new(TaskTestSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Workspaces != nil {
		in, out := &in.Workspaces, &out.Workspaces
		*out = make([]v1.WorkspaceBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AllTriesMustSucceed != nil {
		in, out := &in.AllTriesMustSucceed, &out.AllTriesMustSucceed
		*out = new(bool)
		**out = **in
	}
	if in.ComputeResources != nil {
		in, out := &in.ComputeResources, &out.ComputeResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestRunSpec.
func (in *TaskTestRunSpec) DeepCopy() *TaskTestRunSpec {
	if in == nil {
		return nil
	}
	out := new(TaskTestRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestRunStatus) DeepCopyInto(out *TaskTestRunStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.TaskTestRunStatusFields.DeepCopyInto(&out.TaskTestRunStatusFields)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestRunStatus.
func (in *TaskTestRunStatus) DeepCopy() *TaskTestRunStatus {
	if in == nil {
		return nil
	}
	out := new(TaskTestRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestRunStatusFields) DeepCopyInto(out *TaskTestRunStatusFields) {
	*out = *in
	if in.TaskTestSpec != nil {
		in, out := &in.TaskTestSpec, &out.TaskTestSpec
		*out = new(TaskTestSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TaskTestName != nil {
		in, out := &in.TaskTestName, &out.TaskTestName
		*out = new(string)
		**out = **in
	}
	if in.TaskRunName != nil {
		in, out := &in.TaskRunName, &out.TaskRunName
		*out = new(string)
		**out = **in
	}
	if in.TaskRunStatus != nil {
		in, out := &in.TaskRunStatus, &out.TaskRunStatus
		*out = new(v1.TaskRunStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = new(ObservedOutcomes)
		(*in).DeepCopyInto(*out)
	}
	if in.RetriesStatus != nil {
		in, out := &in.RetriesStatus, &out.RetriesStatus
		*out = make(RetriesStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestRunStatusFields.
func (in *TaskTestRunStatusFields) DeepCopy() *TaskTestRunStatusFields {
	if in == nil {
		return nil
	}
	out := new(TaskTestRunStatusFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestRunTemplate) DeepCopyInto(out *TaskTestRunTemplate) {
	*out = *in
	if in.Workspaces != nil {
		in, out := &in.Workspaces, &out.Workspaces
		*out = make([]v1.WorkspaceBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComputeResources != nil {
		in, out := &in.ComputeResources, &out.ComputeResources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestRunTemplate.
func (in *TaskTestRunTemplate) DeepCopy() *TaskTestRunTemplate {
	if in == nil {
		return nil
	}
	out := new(TaskTestRunTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in TaskTestRunTemplateMap) DeepCopyInto(out *TaskTestRunTemplateMap) {
	{
		in := &in
		*out = make(TaskTestRunTemplateMap, len(*in))
		for key, val := range *in {
			var outVal *TaskTestRunTemplate
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(TaskTestRunTemplate)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestRunTemplateMap.
func (in TaskTestRunTemplateMap) DeepCopy() TaskTestRunTemplateMap {
	if in == nil {
		return nil
	}
	out := new(TaskTestRunTemplateMap)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestSpec) DeepCopyInto(out *TaskTestSpec) {
	*out = *in
	if in.TaskRef != nil {
		in, out := &in.TaskRef, &out.TaskRef
		*out = new(SimpleTaskRef)
		**out = **in
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = new(TaskTestInputs)
		(*in).DeepCopyInto(*out)
	}
	if in.Expects != nil {
		in, out := &in.Expects, &out.Expects
		*out = new(ExpectedOutcomes)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestSpec.
func (in *TaskTestSpec) DeepCopy() *TaskTestSpec {
	if in == nil {
		return nil
	}
	out := new(TaskTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestSuite) DeepCopyInto(out *TaskTestSuite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestSuite.
func (in *TaskTestSuite) DeepCopy() *TaskTestSuite {
	if in == nil {
		return nil
	}
	out := new(TaskTestSuite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskTestSuite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestSuiteList) DeepCopyInto(out *TaskTestSuiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskTestSuite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestSuiteList.
func (in *TaskTestSuiteList) DeepCopy() *TaskTestSuiteList {
	if in == nil {
		return nil
	}
	out := new(TaskTestSuiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskTestSuiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestSuiteRef) DeepCopyInto(out *TaskTestSuiteRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestSuiteRef.
func (in *TaskTestSuiteRef) DeepCopy() *TaskTestSuiteRef {
	if in == nil {
		return nil
	}
	out := new(TaskTestSuiteRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestSuiteRun) DeepCopyInto(out *TaskTestSuiteRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestSuiteRun.
func (in *TaskTestSuiteRun) DeepCopy() *TaskTestSuiteRun {
	if in == nil {
		return nil
	}
	out := new(TaskTestSuiteRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskTestSuiteRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestSuiteRunList) DeepCopyInto(out *TaskTestSuiteRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskTestSuiteRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestSuiteRunList.
func (in *TaskTestSuiteRunList) DeepCopy() *TaskTestSuiteRunList {
	if in == nil {
		return nil
	}
	out := new(TaskTestSuiteRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskTestSuiteRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestSuiteRunSpec) DeepCopyInto(out *TaskTestSuiteRunSpec) {
	*out = *in
	if in.TaskTestSuiteRef != nil {
		in, out := &in.TaskTestSuiteRef, &out.TaskTestSuiteRef
		*out = new(TaskTestSuiteRef)
		**out = **in
	}
	if in.TaskTestSuiteSpec != nil {
		in, out := &in.TaskTestSuiteSpec, &out.TaskTestSuiteSpec
		*out = new(TaskTestSuiteSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultRunSpecTemplate != nil {
		in, out := &in.DefaultRunSpecTemplate, &out.DefaultRunSpecTemplate
		*out = new(TaskTestRunTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.RunSpecs != nil {
		in, out := &in.RunSpecs, &out.RunSpecs
		*out = make([]SuiteTaskTestRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RunSpecMap != nil {
		in, out := &in.RunSpecMap, &out.RunSpecMap
		*out = make(TaskTestRunTemplateMap, len(*in))
		for key, val := range *in {
			var outVal *TaskTestRunTemplate
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(TaskTestRunTemplate)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestSuiteRunSpec.
func (in *TaskTestSuiteRunSpec) DeepCopy() *TaskTestSuiteRunSpec {
	if in == nil {
		return nil
	}
	out := new(TaskTestSuiteRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestSuiteRunStatus) DeepCopyInto(out *TaskTestSuiteRunStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.TaskTestSuiteRunStatusFields.DeepCopyInto(&out.TaskTestSuiteRunStatusFields)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestSuiteRunStatus.
func (in *TaskTestSuiteRunStatus) DeepCopy() *TaskTestSuiteRunStatus {
	if in == nil {
		return nil
	}
	out := new(TaskTestSuiteRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestSuiteRunStatusFields) DeepCopyInto(out *TaskTestSuiteRunStatusFields) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.TaskTestSuiteName != nil {
		in, out := &in.TaskTestSuiteName, &out.TaskTestSuiteName
		*out = new(string)
		**out = **in
	}
	if in.TaskTestSuiteSpec != nil {
		in, out := &in.TaskTestSuiteSpec, &out.TaskTestSuiteSpec
		*out = new(TaskTestSuiteSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CurrentSuiteTest != nil {
		in, out := &in.CurrentSuiteTest, &out.CurrentSuiteTest
		*out = new(string)
		**out = **in
	}
	if in.TaskTestRunStatuses != nil {
		in, out := &in.TaskTestRunStatuses, &out.TaskTestRunStatuses
		*out = make(map[string]*TaskTestRunStatus, len(*in))
		for key, val := range *in {
			var outVal *TaskTestRunStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(TaskTestRunStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestSuiteRunStatusFields.
func (in *TaskTestSuiteRunStatusFields) DeepCopy() *TaskTestSuiteRunStatusFields {
	if in == nil {
		return nil
	}
	out := new(TaskTestSuiteRunStatusFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTestSuiteSpec) DeepCopyInto(out *TaskTestSuiteSpec) {
	*out = *in
	if in.TaskTests != nil {
		in, out := &in.TaskTests, &out.TaskTests
		*out = make([]SuiteTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTestSuiteSpec.
func (in *TaskTestSuiteSpec) DeepCopy() *TaskTestSuiteSpec {
	if in == nil {
		return nil
	}
	out := new(TaskTestSuiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationPolicy) DeepCopyInto(out *VerificationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationPolicy.
func (in *VerificationPolicy) DeepCopy() *VerificationPolicy {
	if in == nil {
		return nil
	}
	out := new(VerificationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerificationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationPolicyList) DeepCopyInto(out *VerificationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VerificationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationPolicyList.
func (in *VerificationPolicyList) DeepCopy() *VerificationPolicyList {
	if in == nil {
		return nil
	}
	out := new(VerificationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerificationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationPolicySpec) DeepCopyInto(out *VerificationPolicySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourcePattern, len(*in))
		copy(*out, *in)
	}
	if in.Authorities != nil {
		in, out := &in.Authorities, &out.Authorities
		*out = make([]Authority, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationPolicySpec.
func (in *VerificationPolicySpec) DeepCopy() *VerificationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(VerificationPolicySpec)
	in.DeepCopyInto(out)
	return out
}
