apiVersion: tekton.dev/v1alpha1
kind: TaskTestSuiteRun
metadata:
  generateName: sample-ttsr-
spec:
  executionMode: Parallel
  taskTestSuiteSpec:
    taskTests:
      - name: task-0
        taskTestSpec:
          taskRef:
            name: hello-task
          expects:
            results:
              - name: current-date
                value: "2025-08-30"
            env:
            - name: HOME
              value: /root
            fileSystemContents:
            - stepName: date-step
              objects:
              - path: /tekton/results/current-date
                type: "TextFile"
                content: "2025-08-30"
            - stepName: time-step
              objects:
              - path: /tekton/results/current-date
                type: "TextFile"
      - name: task-1
        taskTestSpec:
          taskRef:
            name: hello-task
          expects:
            results:
              - name: current-date
                value: "2025-08-30"
            env:
            - name: HOME
              value: /root
            fileSystemContents:
            - stepName: date-step
              objects:
              - path: /tekton/results/current-date
                type: "TextFile"
                content: "2025-08-29"
            - stepName: time-step
              objects:
              - path: /tekton/results/current-date
                type: "TextFile"
        retries: 1
