apiVersion: tekton.dev/v1alpha1
kind: TaskTestSuiteRun
metadata:
  generateName: sample-ttsr-
spec:
  executionMode: Sequential
  defaultRunSpecTemplate:
    workspaces:
      - name: time-workspace
        emptyDir: {}
  taskTestSuiteSpec:
    taskTests:
      - name: task-0
        taskTestSpec:
          taskRef:
            name: hello-task
          inputs:
            workspaceContents:
              - name: time-workspace
                objects:
                  - path: test/time
                    type: TextFile
                    content: "12:34:56"
          expects:
            results:
              - name: current-date
                value: "2025-09-16"
            env:
            - name: HOME
              value: /root
            fileSystemContents:
            - stepName: date-step
              objects:
              - path: /tekton/results/current-date
                type: "TextFile"
                content: "2025-09-16"
            - stepName: time-step
              objects:
              - path: /tekton/results/current-date
                type: "TextFile"
      - name: task-1
        taskTestSpec:
          taskRef:
            name: hello-task
          inputs:
            workspaceContents:
              - name: time-workspace
                objects:
                  - path: test/time
                    type: TextFile
                    content: "12:34:56"
          expects:
            results:
              - name: current-date
                value: "2025-09-16"
            env:
            - name: HOME
              value: /root
            fileSystemContents:
            - stepName: date-step
              objects:
              - path: /tekton/results/current-date
                type: "TextFile"
                content: "2025-09-16"
            - stepName: time-step
              objects:
              - path: /tekton/results/current-date
                type: "TextFile"
