apiVersion: tekton.dev/v1alpha1
kind: TaskTest
metadata:
  name: git-clone-tt
spec:
  taskRef:
    name: git-clone
  inputs:
    params:
    - name: url
      value: https://github.com/jlux98/pipeline-with-ttf
    - name: revision
      value: main
    - name: deleteExisting
      value: false
    - name: subdirectory
      value: ttf-test
  expects:
    results:
    - name: commit
      value: 1eec5fb00ea0dc520b0aa36db51d534ade4a0af5
    executionTimeBelow: 18s
