apiVersion: tekton.dev/v1alpha1
kind: TaskTest
metadata:
  name: git-clone-tt
spec:
  taskRef:
    name: git-clone
  inputs:
    params:
    - name: url
      value: https://github.com/jlux98/pipeline-with-ttf
    - name: revision
      value: main
    - name: deleteExisting
      value: false
    - name: subdirectory
      value: ttf-test
  expects:
    results:
    - name: commit
      value: 2c4f354762a202d58f917038dd53d5b66523e45e
    executionTimeBelow: 18s
