apiVersion: tekton.dev/v1alpha1
kind: TaskTestRun
metadata:
  generateName: sample-ttr-
  namespace: default
spec:
  taskTestSpec:
    taskRef:
      name: hello-task
    inputs:
      workspaceContents:
        - name: time-workspace
          objects:
            - path: test/time
              type: TextFile
              content: "12:34:56"
    expects:
      results:
        - name: current-date
          value: "2025-08-31"
        - name: current-time
          value: "12:34:56"
      env:
      - name: HOME
        value: /root
      fileSystemContents:
      - stepName: date-step
        objects:
        - path: /tekton/results/current-date
          type: "TextFile"
          content: "2025-08-31"
      - stepName: time-step
        objects:
        - path: /tekton/results/current-date
          type: "TextFile"
  retries: 1
  # workspaces:
  # - name: time-workspace
  #   # volumeClaimTemplate:
  #   #   spec:
  #   #     accessModes:
  #   #     - ReadWriteOnce
  #   #     resources:
  #   #       requests:
  #   #         storage: 10Mi
  #   emptyDir: {}
