apiVersion: tekton.dev/v1alpha1
kind: TaskTestRun
metadata:
  generateName: sample-ttr-
  namespace: default
spec:
  taskTestSpec:
    taskRef:
      name: hello-task
    expected:
      results:
        - name: current-date
          value: "2025-08-24"
      env:
      - name: HOME
        value: /root
      fileSystemContents:
      - stepName: date-step
        objects:
        - path: /tekton/results/current-date
          type: "TextFile"
          content: "2025-08-24"
      - stepName: time-step
        objects:
        - path: /tekton/results/current-date
          type: "TextFile"
