/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	pipelinev1alpha1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TaskTestSuiteLister helps list TaskTestSuites.
// All objects returned here must be treated as read-only.
type TaskTestSuiteLister interface {
	// List lists all TaskTestSuites in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pipelinev1alpha1.TaskTestSuite, err error)
	// TaskTestSuites returns an object that can list and get TaskTestSuites.
	TaskTestSuites(namespace string) TaskTestSuiteNamespaceLister
	TaskTestSuiteListerExpansion
}

// taskTestSuiteLister implements the TaskTestSuiteLister interface.
type taskTestSuiteLister struct {
	listers.ResourceIndexer[*pipelinev1alpha1.TaskTestSuite]
}

// NewTaskTestSuiteLister returns a new TaskTestSuiteLister.
func NewTaskTestSuiteLister(indexer cache.Indexer) TaskTestSuiteLister {
	return &taskTestSuiteLister{listers.New[*pipelinev1alpha1.TaskTestSuite](indexer, pipelinev1alpha1.Resource("tasktestsuite"))}
}

// TaskTestSuites returns an object that can list and get TaskTestSuites.
func (s *taskTestSuiteLister) TaskTestSuites(namespace string) TaskTestSuiteNamespaceLister {
	return taskTestSuiteNamespaceLister{listers.NewNamespaced[*pipelinev1alpha1.TaskTestSuite](s.ResourceIndexer, namespace)}
}

// TaskTestSuiteNamespaceLister helps list and get TaskTestSuites.
// All objects returned here must be treated as read-only.
type TaskTestSuiteNamespaceLister interface {
	// List lists all TaskTestSuites in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pipelinev1alpha1.TaskTestSuite, err error)
	// Get retrieves the TaskTestSuite from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*pipelinev1alpha1.TaskTestSuite, error)
	TaskTestSuiteNamespaceListerExpansion
}

// taskTestSuiteNamespaceLister implements the TaskTestSuiteNamespaceLister
// interface.
type taskTestSuiteNamespaceLister struct {
	listers.ResourceIndexer[*pipelinev1alpha1.TaskTestSuite]
}
