/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	pipelinev1alpha1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TaskTestSuiteRunLister helps list TaskTestSuiteRuns.
// All objects returned here must be treated as read-only.
type TaskTestSuiteRunLister interface {
	// List lists all TaskTestSuiteRuns in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pipelinev1alpha1.TaskTestSuiteRun, err error)
	// TaskTestSuiteRuns returns an object that can list and get TaskTestSuiteRuns.
	TaskTestSuiteRuns(namespace string) TaskTestSuiteRunNamespaceLister
	TaskTestSuiteRunListerExpansion
}

// taskTestSuiteRunLister implements the TaskTestSuiteRunLister interface.
type taskTestSuiteRunLister struct {
	listers.ResourceIndexer[*pipelinev1alpha1.TaskTestSuiteRun]
}

// NewTaskTestSuiteRunLister returns a new TaskTestSuiteRunLister.
func NewTaskTestSuiteRunLister(indexer cache.Indexer) TaskTestSuiteRunLister {
	return &taskTestSuiteRunLister{listers.New[*pipelinev1alpha1.TaskTestSuiteRun](indexer, pipelinev1alpha1.Resource("tasktestsuiterun"))}
}

// TaskTestSuiteRuns returns an object that can list and get TaskTestSuiteRuns.
func (s *taskTestSuiteRunLister) TaskTestSuiteRuns(namespace string) TaskTestSuiteRunNamespaceLister {
	return taskTestSuiteRunNamespaceLister{listers.NewNamespaced[*pipelinev1alpha1.TaskTestSuiteRun](s.ResourceIndexer, namespace)}
}

// TaskTestSuiteRunNamespaceLister helps list and get TaskTestSuiteRuns.
// All objects returned here must be treated as read-only.
type TaskTestSuiteRunNamespaceLister interface {
	// List lists all TaskTestSuiteRuns in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pipelinev1alpha1.TaskTestSuiteRun, err error)
	// Get retrieves the TaskTestSuiteRun from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*pipelinev1alpha1.TaskTestSuiteRun, error)
	TaskTestSuiteRunNamespaceListerExpansion
}

// taskTestSuiteRunNamespaceLister implements the TaskTestSuiteRunNamespaceLister
// interface.
type taskTestSuiteRunNamespaceLister struct {
	listers.ResourceIndexer[*pipelinev1alpha1.TaskTestSuiteRun]
}
