/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	pipelinev1alpha1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TaskTestLister helps list TaskTests.
// All objects returned here must be treated as read-only.
type TaskTestLister interface {
	// List lists all TaskTests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pipelinev1alpha1.TaskTest, err error)
	// TaskTests returns an object that can list and get TaskTests.
	TaskTests(namespace string) TaskTestNamespaceLister
	TaskTestListerExpansion
}

// taskTestLister implements the TaskTestLister interface.
type taskTestLister struct {
	listers.ResourceIndexer[*pipelinev1alpha1.TaskTest]
}

// NewTaskTestLister returns a new TaskTestLister.
func NewTaskTestLister(indexer cache.Indexer) TaskTestLister {
	return &taskTestLister{listers.New[*pipelinev1alpha1.TaskTest](indexer, pipelinev1alpha1.Resource("tasktest"))}
}

// TaskTests returns an object that can list and get TaskTests.
func (s *taskTestLister) TaskTests(namespace string) TaskTestNamespaceLister {
	return taskTestNamespaceLister{listers.NewNamespaced[*pipelinev1alpha1.TaskTest](s.ResourceIndexer, namespace)}
}

// TaskTestNamespaceLister helps list and get TaskTests.
// All objects returned here must be treated as read-only.
type TaskTestNamespaceLister interface {
	// List lists all TaskTests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pipelinev1alpha1.TaskTest, err error)
	// Get retrieves the TaskTest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*pipelinev1alpha1.TaskTest, error)
	TaskTestNamespaceListerExpansion
}

// taskTestNamespaceLister implements the TaskTestNamespaceLister
// interface.
type taskTestNamespaceLister struct {
	listers.ResourceIndexer[*pipelinev1alpha1.TaskTest]
}
