/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	pipelinev1alpha1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TaskTestRunLister helps list TaskTestRuns.
// All objects returned here must be treated as read-only.
type TaskTestRunLister interface {
	// List lists all TaskTestRuns in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pipelinev1alpha1.TaskTestRun, err error)
	// TaskTestRuns returns an object that can list and get TaskTestRuns.
	TaskTestRuns(namespace string) TaskTestRunNamespaceLister
	TaskTestRunListerExpansion
}

// taskTestRunLister implements the TaskTestRunLister interface.
type taskTestRunLister struct {
	listers.ResourceIndexer[*pipelinev1alpha1.TaskTestRun]
}

// NewTaskTestRunLister returns a new TaskTestRunLister.
func NewTaskTestRunLister(indexer cache.Indexer) TaskTestRunLister {
	return &taskTestRunLister{listers.New[*pipelinev1alpha1.TaskTestRun](indexer, pipelinev1alpha1.Resource("tasktestrun"))}
}

// TaskTestRuns returns an object that can list and get TaskTestRuns.
func (s *taskTestRunLister) TaskTestRuns(namespace string) TaskTestRunNamespaceLister {
	return taskTestRunNamespaceLister{listers.NewNamespaced[*pipelinev1alpha1.TaskTestRun](s.ResourceIndexer, namespace)}
}

// TaskTestRunNamespaceLister helps list and get TaskTestRuns.
// All objects returned here must be treated as read-only.
type TaskTestRunNamespaceLister interface {
	// List lists all TaskTestRuns in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pipelinev1alpha1.TaskTestRun, err error)
	// Get retrieves the TaskTestRun from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*pipelinev1alpha1.TaskTestRun, error)
	TaskTestRunNamespaceListerExpansion
}

// taskTestRunNamespaceLister implements the TaskTestRunNamespaceLister
// interface.
type taskTestRunNamespaceLister struct {
	listers.ResourceIndexer[*pipelinev1alpha1.TaskTestRun]
}
